def write_cpw_cif(gnd_width, slot_width, sig_width, length,
                  metal_layer=1, slot_layer=2,
                  filename="cpw.cif"):
    """
    Generates a CIF file for a CPW structure.
    Units: microns (you can scale if needed)
    """

    def rect(x1, y1, x2, y2):
        """Return CIF rectangle command"""
        return f"B {x2-x1} {y2-y1} {int((x1+x2)/2)} {int((y1+y2)/2)};\n"

    with open(filename, "w") as f:
        # Header
        f.write("(CPW CIF generated by script)\n")
        f.write("DS 1 1 1;\n")   # Define structure

        # -----------------------
        # METAL LAYER
        # -----------------------
        f.write(f"L {metal_layer};\n")

        # Signal line
        f.write(rect(-sig_width/2, 0, sig_width/2, length))

        # Left ground
        f.write(rect(-sig_width/2 - slot_width - gnd_width, 0,
                     -sig_width/2 - slot_width, length))

        # Right ground
        f.write(rect(sig_width/2 + slot_width, 0,
                     sig_width/2 + slot_width + gnd_width, length))

        # -----------------------
        # SLOT LAYER
        # -----------------------
        f.write(f"L {slot_layer};\n")

        # Left slot
        f.write(rect(-sig_width/2 - slot_width, 0,
                     -sig_width/2, length))

        # Right slot
        f.write(rect(sig_width/2, 0,
                     sig_width/2 + slot_width, length))

        # End structure
        f.write("DF;\n")
        f.write("E;\n")

    print(f"CIF file '{filename}' created successfully.")



write_cpw_cif(
        gnd_width=180,
        slot_width=24,
        sig_width=40,
        length=1000
    )